# Generated by Django 3.2.4 on 2022-12-12 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_equipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='equipo',
            new_name='equipo_nombre',
        ),
    ]
