# Generated by Django 3.2.4 on 2022-12-26 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0002_alter_encuesta_fechacreacion'),
        ('user', '0003_rename_equipo_user_equipo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='equipo_nombre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='encuesta.equipos', verbose_name='Equipo de trabajo'),
        ),
    ]
