# Generated by Django 3.2.4 on 2022-11-25 13:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Atencion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Atención',
                'verbose_name_plural': 'Atención',
                'db_table': 'atencion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaInactividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria_inactividad', models.CharField(max_length=50, verbose_name='Categoria de Inactividad')),
            ],
            options={
                'verbose_name': 'Categoria de Inactividad',
                'verbose_name_plural': 'Categorias de Inactividad',
                'db_table': 'categoria_inactividad',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaOcupacional',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria_ocupacion', models.CharField(max_length=50, verbose_name='Categoria Ocupacional')),
            ],
            options={
                'verbose_name': 'Categoria Ocupacional',
                'verbose_name_plural': 'Categoria Ocupacional',
                'db_table': 'cat_ocupacional',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CentroAbordaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('abordaje_como_llega', models.CharField(max_length=50, verbose_name='¿Como Llega al Centro de Abordaje?')),
            ],
            options={
                'verbose_name': 'Centro de Abordaje',
                'verbose_name_plural': 'Centros de Abordaje',
                'db_table': 'centro_abordaje',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dpto', models.CharField(max_length=50, verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('distrito', models.CharField(max_length=50, verbose_name='Distrito')),
                ('dpto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.departamento', verbose_name='id_dpto')),
            ],
            options={
                'verbose_name': 'Distrito',
                'verbose_name_plural': '-distritos',
                'db_table': 'distrito',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nivel', models.CharField(max_length=50, verbose_name='Nivel Educativo (Maximo Alcanzado)')),
            ],
            options={
                'verbose_name': 'Nivel Educativo',
                'verbose_name_plural': 'Niveles Educativos',
                'db_table': 'nivel_educativo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado_civil', models.CharField(max_length=50, verbose_name='Estado CIvil')),
            ],
            options={
                'verbose_name': 'Estado Civil',
                'verbose_name_plural': 'Estado Civil',
                'db_table': 'estado_civil',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='IncumbenciaSeguridad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('incumbencia_seguridad', models.CharField(max_length=50, verbose_name='Ocupacion en la fuerza de seguridad, segun incumbencia')),
            ],
            options={
                'verbose_name': 'Incumbencia Seguridad',
                'verbose_name_plural': 'Incumbencias Seguridad',
                'db_table': 'incumbencia_seguridad',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MiembrosConvivientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre:')),
                ('edad', models.CharField(max_length=50, verbose_name='Edad:')),
                ('parentesco', models.CharField(max_length=50, verbose_name='Parentesco:')),
                ('hijos', models.CharField(max_length=50, verbose_name='Hijos - Propios Anteriores de la PSVG')),
            ],
            options={
                'verbose_name': 'Miembros Convivientes',
                'verbose_name_plural': 'Miembros Convivientes',
                'db_table': 'miembros_convivientes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nacionalidad', models.CharField(max_length=50, verbose_name='Nacionalidad ')),
            ],
            options={
                'verbose_name': 'Nacionalidad',
                'verbose_name_plural': 'Nacionalidades',
                'db_table': 'nacionalidad',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('opcion', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'Opcion',
                'verbose_name_plural': 'Opciones',
                'db_table': 'opcion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SeisMeses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Tiempo Tratamiento',
                'verbose_name_plural': 'Tiempo Tratamiento',
                'db_table': 'tiempo_tratamiento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SituacionLaboral',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('situacion_laboral', models.CharField(max_length=50, verbose_name='Situacion Laboral')),
            ],
            options={
                'verbose_name': 'Situacion Laboral',
                'verbose_name_plural': 'Situaciones Laborales',
                'db_table': 'situacion_laboral',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre')),
                ('direccion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Direccion')),
                ('telefono', models.PositiveIntegerField(blank=True, null=True, verbose_name='Telefono')),
                ('tipoatencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='encuesta.atencion', verbose_name='Atención')),
                ('ubicaciondpto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dpto_equipos', to='encuesta.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'equipo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('date_cration', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechacreacion', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Fecha Ficha')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('nro_dni', models.CharField(max_length=11, unique=True, verbose_name='N° DU')),
                ('fecha_nacimiento', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('calle', models.CharField(blank=True, max_length=50, null=True, verbose_name='Calle')),
                ('nrocalle', models.PositiveIntegerField(blank=True, null=True, verbose_name='Calle Nro')),
                ('mbt', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mnza/Mblck/Torre')),
                ('pdc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Piso/Casa/Dpto')),
                ('bfpa', models.CharField(blank=True, max_length=50, null=True, verbose_name='Barrio/Finca/Puesto/Asentamiento')),
                ('telefono', models.PositiveIntegerField(blank=True, null=True, verbose_name='Telefono')),
                ('telefonoa', models.PositiveIntegerField(blank=True, null=True, verbose_name='Telefono Alternativo')),
                ('osnombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de la Obra Social')),
                ('actividad_laboral', models.CharField(blank=True, max_length=50, null=True, verbose_name='Actividad que Realiza')),
                ('domicilio_laboral', models.CharField(blank=True, max_length=50, null=True, verbose_name='Domicilio Laboral')),
                ('ayduda_centroa_cual', models.CharField(blank=True, max_length=50, null=True, verbose_name='Especificar Cual')),
                ('jfinterviniente', models.CharField(blank=True, max_length=50, null=True, verbose_name='Juzgado/Fiscalía Interviniente')),
                ('obasistencia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Obligatoriedad de Asistencia')),
                ('prohibicion_quien', models.CharField(blank=True, max_length=50, null=True, verbose_name='Hacia quien/es')),
                ('antecedentes_otros', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Delito Contra la Persona', 'Delito Contra la Persona'), ('Delito contra la vida', 'Delito contra la vida'), ('Intento de femicidio', 'Intento de femicidio'), ('Lesiones Leves', 'Lesiones Leves'), ('Lesiones Graves', 'Lesiones Graves'), ('Lesiones Gravisimas', 'Lesiones Gravisimas'), ('Abuso de Armas (con lesiones)', 'Abuso de Armas (con lesiones)'), ('Abuso de Armas (sin lesiones)', 'Abuso de Armas (sin lesiones)'), ('Abandono de la persona', 'Abandono de la persona'), ('Delitos contra la integridad sexual', 'Delitos contra la integridad sexual'), ('Delitos contra la libertad (Amenaza)', ' Delitos contra la libertad (Amenaza)'), ('Delitos contra la libertad (Violacion de Domicilio)', ' Delitos contra la libertad (Violacion de Domicilio)'), ('Delitos contra la propiedad (Hurto)', ' Delitos contra la propiedad (Hurto)'), ('Delitos contra la propiedad (Robo)', ' Delitos contra la propiedad (Robo)'), ('Violacion de Domicilio (Extorsión)', ' Violacion de Domicilio (Extorsión)'), ('Violacion de Domicilio (Usurpación)', ' Violacion de Domicilio (Usurpación)'), ('Violacion de Domicilio (Daños)', ' Violacion de Domicilio (Daños)'), ('Violacion de Domicilio (Desobediencia)', ' Violacion de Domicilio (Desobediencia)')], max_length=538, null=True)),
                ('ddnombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre/s')),
                ('ddapellido', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido/s')),
                ('ddnro_dni', models.CharField(max_length=11, unique=True, verbose_name='N° DU')),
                ('atps_medicacion_nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre - Medicación')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='OBSERVACIONES')),
                ('tv_personal', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Fisica', 'Fisica'), ('Violencia Psicologica', 'Violencia Psicologica'), ('Violencia Sexual', 'Violencia Sexual'), ('Violencia Economica y patrimonial', 'Violencia Economica y patrimonial'), ('Violencia Simbolica', 'Violencia Simbolica'), ('Violencia Ambiental', 'Violencia Ambiental')], max_length=200, null=True)),
                ('tv_familiar', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Fisica', 'Fisica'), ('Violencia Psicologica', 'Violencia Psicologica'), ('Violencia Sexual', 'Violencia Sexual'), ('Violencia Economica y patrimonial', 'Violencia Economica y patrimonial'), ('Violencia Simbolica', 'Violencia Simbolica'), ('Violencia Ambiental', 'Violencia Ambiental')], max_length=200, null=True)),
                ('modalidad_personal', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Domestica', 'Domestica'), ('Institucional', 'Institucional'), ('Laboral', 'Laboral'), ('Contra la libertad reprodictiva y obstétrica', 'Contra la libertad reprodictiva y obstétrica'), ('Mediatica', 'Mediatica')], max_length=200, null=True)),
                ('modalidad_familiar', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Domestica', 'Domestica'), ('Institucional', 'Institucional'), ('Laboral', 'Laboral'), ('Contra la libertad reprodictiva y obstétrica', 'Contra la libertad reprodictiva y obstétrica'), ('Mediatica', 'Mediatica')], max_length=200, null=True)),
                ('agresor', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Condicion Migratoria', 'Condicion Migratoria'), ('Estres Psicosocial', 'Estres Psicosocial'), ('Abuso de Sustancias Psicoactivas', 'Abuso de Sustancias Psicoactivas'), ('Antecedentes de Violencia en su Biografia', 'Antecedentes de Violencia en su Biografia'), ('Tenencia y uso de Armas', 'Tenencia y uso de Armas'), ('Antecedentes depresivos', 'Antecedentes depresivos'), ('Presencia de miedo o rechazo a los abandonos', 'Presencia de miedo o rechazo a los abandonos'), ('Inestabilidad anímica', 'Inestabilidad anímica'), ('Egocentrismo', 'Egocentrismo')], max_length=200, null=True)),
                ('mujer', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Vulnerabilidad Social', 'Vulnerabilidad Social'), ('Retractarse de separacion o denuncia al agresor', 'Retractarse de separacion o denuncia al agresor'), ('Presencia de hijo no biológico en la convivencia con el agresor', 'Presencia de hijo no biológico en la convivencia con el agresor')], max_length=200, null=True)),
                ('situacion', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Relacion en convivencia o matrimonial', 'Relacion en convivencia o matrimonial'), ('Solicitud de separacion por parte de la mujer', 'Solicitud de separacion por parte de la mujer'), ('ideación de celos del estilo posesivos', 'ideación de celos del estilo posesivos'), ('Transitar embarazo', 'Transitar embarazo'), ('presedente de conductas de acoso', 'presedente de conductas de acoso'), ('conductas de amenazas', 'conductas de amenazas')], max_length=200, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('acceso_arma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acceso_arma', to='encuesta.opcion', verbose_name='¿Tiene Acceso a armas de fuego o similar?')),
                ('antecedentes_judiciales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes_judiciales', to='encuesta.opcion', verbose_name='Antecedentes Judiciales')),
                ('atps_medicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicacion', to='encuesta.opcion', verbose_name='Toma Medicación')),
                ('atps_medicacion_vigente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicacion_vigente', to='encuesta.opcion', verbose_name='Medicación vigente')),
                ('atps_psico_psiqui_6_meses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atps_psico_psiqui_6_meses', to='encuesta.seismeses', verbose_name='Tratamiento 6 meses')),
                ('atps_psicologico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psicologico', to='encuesta.opcion', verbose_name='Antecedente Psicologico')),
                ('atps_psiquiatrico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psiquiatrico', to='encuesta.opcion', verbose_name='Antecedente Psiquiatrico')),
                ('ayuda_centroa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='encuesta.centroabordaje', verbose_name='¿Como Llega al Centro de Abordaje?')),
                ('categoria_inactividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='encuesta.categoriainactividad', verbose_name='Categoria Inactividad')),
                ('categoria_ocupacional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='encuesta.categoriaocupacional', verbose_name='Categoria Ocupacional')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='encuesta.departamento', verbose_name='Departamento')),
                ('distrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='encuesta.distrito', verbose_name='Distrito')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='encuesta.equipos', verbose_name='Equipo')),
                ('estado_civil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='encuesta.estadocivil', verbose_name='Estado Civil')),
                ('incumbencia_seguridad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='encuesta.incumbenciaseguridad', verbose_name='Ocupación en la fuerza de seguridad, segun incumbencia')),
                ('miembros_intervinientes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='encuesta.miembrosconvivientes', verbose_name='Miembros Convivientes')),
                ('nacionalidad', models.ForeignKey(default=9, null=True, on_delete=django.db.models.deletion.CASCADE, to='encuesta.nacionalidad', verbose_name='Nacionalidad')),
                ('nivel_educacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='encuesta.educacion', verbose_name='Educacion (Maximo Nivel Alcanzado)')),
                ('ostiene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ostiene', to='encuesta.opcion', verbose_name='Tiene Obra Social')),
                ('prohibicion_acercamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prohibicion_acercamiento', to='encuesta.opcion', verbose_name='Prohibicion de Acercamiento')),
                ('pulsera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pulsera', to='encuesta.opcion', verbose_name='Pulsera Electronica')),
                ('situacion_laboral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='encuesta.situacionlaboral', verbose_name='Situacion Laboral')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_update', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Encuesta',
                'verbose_name_plural': 'Encuestas',
                'db_table': 'encuesta',
                'ordering': ['id'],
            },
        ),
    ]
