# Generated by Django 3.2.4 on 2022-10-28 12:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaInactividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria_inactividad', models.CharField(max_length=50, verbose_name='Categoria de Inactividad')),
            ],
            options={
                'verbose_name': 'Categoria de Inactividad',
                'verbose_name_plural': 'Categorias de Inactividad',
                'db_table': 'categoria_inactividad',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaOcupacional',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria_ocupacion', models.CharField(max_length=50, verbose_name='Categoria Ocupacional')),
            ],
            options={
                'verbose_name': 'Categoria Ocupacional',
                'verbose_name_plural': 'Categoria Ocupacional',
                'db_table': 'cat_ocupacional',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CentroAbordaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('abordaje_como_llega', models.CharField(max_length=50, verbose_name='¿Como Llega al Centro de Abordaje?')),
            ],
            options={
                'verbose_name': 'Centro de Abordaje',
                'verbose_name_plural': 'Centros de Abordaje',
                'db_table': 'centro_abordaje',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dpto', models.CharField(max_length=50, verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('distrito', models.CharField(max_length=50, verbose_name='Distrito')),
                ('dpto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='encuesta.departamento', verbose_name='id_dpto')),
            ],
            options={
                'verbose_name': 'Distrito',
                'verbose_name_plural': '-distritos',
                'db_table': 'distrito',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nivel', models.CharField(max_length=50, verbose_name='Nivel Educativo (Maximo Alcanzado)')),
            ],
            options={
                'verbose_name': 'Nivel Educativo',
                'verbose_name_plural': 'Niveles Educativos',
                'db_table': 'nivel_educativo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado_civil', models.CharField(max_length=50, verbose_name='Estado CIvil')),
            ],
            options={
                'verbose_name': 'Estado Civil',
                'verbose_name_plural': 'Estado Civil',
                'db_table': 'estado_civil',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='IncumbenciaSeguridad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('incumbencia_seguridad', models.CharField(max_length=50, verbose_name='Ocupacion en la fuerza de seguridad, segun incumbencia')),
            ],
            options={
                'verbose_name': 'Incumbencia Seguridad',
                'verbose_name_plural': 'Incumbencias Seguridad',
                'db_table': 'incumbencia_seguridad',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MiembrosConvivientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre:')),
                ('edad', models.CharField(max_length=50, verbose_name='Edad:')),
                ('parentesco', models.CharField(max_length=50, verbose_name='Parentesco:')),
                ('hijos', models.CharField(max_length=50, verbose_name='Hijos - Propios Anteriores de la PSVG')),
            ],
            options={
                'verbose_name': 'Miembros Convivientes',
                'verbose_name_plural': 'Miembros Convivientes',
                'db_table': 'miembros_convivientes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ModalidadFamiliar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('domestica', models.CharField(max_length=50)),
                ('institucional', models.BooleanField(default=False)),
                ('laboral', models.BooleanField(default=False)),
                ('libertad', models.BooleanField(default=False)),
                ('mediatica', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Modalidad - Familiar',
                'verbose_name_plural': 'Modalidad - Familiar',
                'db_table': 'modalidad_familiar',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ModalidadPersonal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('domestica', models.CharField(max_length=50)),
                ('institucional', models.BooleanField(default=False)),
                ('laboral', models.BooleanField(default=False)),
                ('libertad', models.BooleanField(default=False)),
                ('mediatica', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Modalidad - Personal',
                'verbose_name_plural': 'Modalidad - Personales',
                'db_table': 'modalidad_personal',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nacionalidad', models.CharField(max_length=50, verbose_name='Nacionalidad')),
            ],
            options={
                'verbose_name': 'Nacionalidad',
                'verbose_name_plural': 'Nacionalidades',
                'db_table': 'nacionalidad',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('opcion', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'Opcion',
                'verbose_name_plural': 'opciones',
                'db_table': 'opcion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SituacionLaboral',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('situacion_laboral', models.CharField(max_length=50, verbose_name='Situacion Laboral')),
            ],
            options={
                'verbose_name': 'Situacion Laboral',
                'verbose_name_plural': 'Situaciones Laborales',
                'db_table': 'situacion_laboral',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoViolenciaFamiliar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fisica', models.CharField(max_length=50)),
                ('psicologica', models.BooleanField(default=False)),
                ('sexual', models.BooleanField(default=False)),
                ('economica', models.BooleanField(default=False)),
                ('simbolica', models.BooleanField(default=False)),
                ('ambiental', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Violencia - Familiar',
                'verbose_name_plural': 'Violencia - Familia',
                'db_table': 'tv_familiar',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoViolenciaPersonal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fisica', models.CharField(max_length=50)),
                ('psicologica', models.BooleanField(default=False)),
                ('sexual', models.BooleanField(default=False)),
                ('economica', models.BooleanField(default=False)),
                ('simbolica', models.BooleanField(default=False)),
                ('ambiental', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Violencia - Personal',
                'verbose_name_plural': 'Violencia - Personales',
                'db_table': 'tv_personal',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('date_cration', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechacreacion', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Fecha Ficha')),
                ('equipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Equipo')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('nro_dni', models.CharField(max_length=11, unique=True, verbose_name='N° DNI')),
                ('fecha_nacimiento', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('calle', models.CharField(blank=True, max_length=50, null=True, verbose_name='Calle')),
                ('nrocalle', models.PositiveIntegerField(blank=True, null=True, verbose_name='Calle Nro')),
                ('mbt', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mnza/Mblck/Torre')),
                ('pdc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Piso/Casa/Dpto')),
                ('bfpa', models.CharField(blank=True, max_length=50, null=True, verbose_name='Barrio/Finca/Puesto/Asentamiento')),
                ('telefono', models.PositiveIntegerField(blank=True, null=True, verbose_name='Telefono')),
                ('telefonoa', models.PositiveIntegerField(blank=True, null=True, verbose_name='Telefono Alternativo')),
                ('osnombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de la Obra Social')),
                ('actividad_laboral', models.CharField(blank=True, max_length=50, null=True, verbose_name='Actividad que Realiza')),
                ('domicilio_laboral', models.CharField(blank=True, max_length=50, null=True, verbose_name='Domicilio Laboral')),
                ('ayduda_centroa_cual', models.CharField(blank=True, max_length=50, null=True, verbose_name='Especificar Cual')),
                ('jfinterviniente', models.CharField(blank=True, max_length=50, null=True, verbose_name='Juzgado/Fiscalía Interviniente')),
                ('obasistencia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Obligatoriedad de Asistencia')),
                ('prohibicion_quien', models.CharField(blank=True, max_length=50, null=True, verbose_name='Hacia quien/es')),
                ('antecedentes_judiciales', models.CharField(blank=True, max_length=200, null=True, verbose_name='Antecedentes Judiciales')),
                ('antecedentes_otros', models.CharField(blank=True, max_length=200, null=True, verbose_name='Otros')),
                ('ddnombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre/s')),
                ('ddapellido', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido/s')),
                ('ddnro_dni', models.CharField(max_length=11, unique=True, verbose_name='N° DNI')),
                ('atps_psico_psiqui', models.CharField(blank=True, max_length=200, null=True, verbose_name='Piscologico Psiquiatrico')),
                ('atps_medicacion_nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Medicación')),
                ('atps_psico_psiqui_6_meses', models.CharField(blank=True, max_length=200, null=True, verbose_name='Duracion 6 meses')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='OBSERVACIONES')),
                ('agresor', multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'Condicion Migratoria'), ('item_key2', 'Estres Psicosocial'), ('item_key3', 'Abuso de Sustancias Psicoactivas'), ('item_key4', 'Antecedentes de Violencia en su Biografia'), ('item_key5', 'Tenencia y uso de Armas'), ('item_key5', 'Antecedentes depresivos'), ('item_key5', 'Presencia de miedo o rechazo a los abandonos'), ('item_key5', 'Inestabilidad anímica'), ('item_key5', 'Egocentrismo')], max_length=89)),
                ('mujer', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Vulnerabilidad Social'), (2, 'Retractarse de separacion o denuncia al agresor'), (3, 'Presencia de hijo no biológico en la convivencia con el agresor'), (4, 'Item title 2.4'), (5, 'Item title 2.5')], max_length=9)),
                ('situacion', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Relacion en convivencia o matrimonial'), (2, 'Solicitud de separacion por parte de la mujer'), (3, 'ideación de celos del estilo posesivos'), (4, 'Transitar embarazo'), (5, 'presedente de conductas de acoso'), (6, 'conductas de amenazas')], max_length=11)),
                ('estado', models.BooleanField(default=True)),
                ('acceso_arma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acceso_arma', to='encuesta.opcion', verbose_name='¿Tiene Acceso a armas de fuego o similar?')),
                ('atps_medicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicacion', to='encuesta.opcion', verbose_name='Toma Medicación')),
                ('atps_medicacion_vigente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicacion_vigente', to='encuesta.opcion', verbose_name='Medicación vigente')),
                ('ayuda_centroa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='encuesta.centroabordaje', verbose_name='¿Como Llega al Centro de Abordaje?')),
                ('categoria_inactividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='encuesta.categoriainactividad', verbose_name='Categoria Inactividad')),
                ('categoria_ocupacional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='encuesta.categoriaocupacional', verbose_name='Categoria Ocupacional')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='encuesta.departamento', verbose_name='Departamento')),
                ('distrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='encuesta.distrito', verbose_name='Distrito')),
                ('estado_civil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='encuesta.estadocivil', verbose_name='Estado Civil')),
                ('incumbencia_seguridad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='encuesta.incumbenciaseguridad', verbose_name='Ocupación en la fuerza de seguridad, segun incumbencia')),
                ('miembros_intervinientes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='encuesta.miembrosconvivientes', verbose_name='Miembros Convivientes')),
                ('modalidad_familiar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='encuesta.modalidadfamiliar', verbose_name='Familiar')),
                ('modalidad_personal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='encuesta.modalidadpersonal', verbose_name='Personal')),
                ('nacionalidad', models.ForeignKey(default=9, null=True, on_delete=django.db.models.deletion.PROTECT, to='encuesta.nacionalidad', verbose_name='Nacionalidad')),
                ('nivel_educacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='encuesta.educacion', verbose_name='Educacion (Maximo Nivel Alcanzado)')),
                ('ostiene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ostiene', to='encuesta.opcion', verbose_name='Tiene Obra Social')),
                ('prohibicion_acercamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prohibicion_acercamiento', to='encuesta.opcion', verbose_name='Prohibicion de Acercamiento')),
                ('pulsera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pulsera', to='encuesta.opcion', verbose_name='Pulsera Electronica')),
                ('situacion_laboral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='encuesta.situacionlaboral', verbose_name='Situacion Laboral')),
                ('tv_familiar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='encuesta.tipoviolenciafamiliar', verbose_name='Familiar')),
                ('tv_personal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='encuesta.tipoviolenciapersonal', verbose_name='Personal')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_update', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Encuesta',
                'verbose_name_plural': 'Encuestas',
                'db_table': 'encuesta',
                'ordering': ['id'],
            },
        ),
    ]
