# Generated by Django 3.2.4 on 2022-08-10 19:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaInactividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria_inactividad', models.CharField(max_length=50, verbose_name='Categoria de Inactividad')),
            ],
            options={
                'verbose_name': 'Categoria de Inactividad',
                'verbose_name_plural': 'Categorias de Inactividad',
                'db_table': 'categoria_inactividad',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaOcupacional',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria_ocupacion', models.CharField(max_length=50, verbose_name='Categoria Ocupacional')),
            ],
            options={
                'verbose_name': 'Categoria Ocupacional',
                'verbose_name_plural': 'Categoria Ocupacional',
                'db_table': 'cat_ocupacional',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CentroAbordaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('abordaje_como_llega', models.CharField(max_length=50, verbose_name='¿Como Llega al Centro de Abordaje?')),
            ],
            options={
                'verbose_name': 'Centro de Abordaje',
                'verbose_name_plural': 'Centros de Abordaje',
                'db_table': 'centro_abordaje',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dpto', models.CharField(max_length=50, verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('distrito', models.CharField(max_length=50, verbose_name='Distrito')),
                ('dpto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='encuesta.departamento', verbose_name='id_dpto')),
            ],
            options={
                'verbose_name': 'Distrito',
                'verbose_name_plural': '-distritos',
                'db_table': 'distrito',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nivel', models.CharField(max_length=50, verbose_name='Nivel Educativo (Maximo Alcanzado)')),
            ],
            options={
                'verbose_name': 'Nivel Educativo',
                'verbose_name_plural': 'Niveles Educativos',
                'db_table': 'nivel_educativo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado_civil', models.CharField(max_length=50, verbose_name='Estado CIvil')),
            ],
            options={
                'verbose_name': 'Estado Civil',
                'verbose_name_plural': 'Estado Civil',
                'db_table': 'estado_civil',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MiembrosConvivientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre:')),
                ('edad', models.CharField(max_length=50, verbose_name='Edad:')),
                ('parentesco', models.CharField(max_length=50, verbose_name='Parentesco:')),
                ('hijos', models.CharField(max_length=50, verbose_name='Hijos - Propios Anteriores de la PSVG')),
            ],
            options={
                'verbose_name': 'Miembros Convivientes',
                'verbose_name_plural': 'Miembros Convivientes',
                'db_table': 'miembros_convivientes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nacionalidad', models.CharField(max_length=50, verbose_name='Nacionalidad')),
            ],
            options={
                'verbose_name': 'Nacionalidad',
                'verbose_name_plural': 'Nacionalidades',
                'db_table': 'nacionalidad',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('opcion', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'Opcion',
                'verbose_name_plural': 'opciones',
                'db_table': 'opcion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SituacionLaboral',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('situacion_laboral', models.CharField(max_length=50, verbose_name='Situacion Laboral')),
            ],
            options={
                'verbose_name': 'Situacion Laboral',
                'verbose_name_plural': 'Situaciones Laborales',
                'db_table': 'situacion_laboral',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('date_cration', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('nro_dni', models.CharField(max_length=11, unique=True, verbose_name='N° DNI')),
                ('fecha_nacimiento', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('edad', models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad')),
                ('calle', models.CharField(blank=True, max_length=50, null=True, verbose_name='Calle')),
                ('rocalle', models.PositiveIntegerField(blank=True, null=True, verbose_name='Calle Nro')),
                ('mbt', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mnza/Mblck/Torre')),
                ('pdc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Piso/Casa/Dpto')),
                ('bfpa', models.CharField(blank=True, max_length=50, null=True, verbose_name='Barrio/Finca/Puesto/Asentamiento')),
                ('telefono', models.PositiveIntegerField(blank=True, null=True, verbose_name='Telefono')),
                ('telefonoa', models.PositiveIntegerField(blank=True, null=True, verbose_name='Telefono Alternativo')),
                ('oscual', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de la Obra Social')),
                ('horas_situacionlaboral', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad de Horas que Trabajo por Semana')),
                ('actividad_laboral', models.CharField(blank=True, max_length=50, null=True, verbose_name='Actividad que Realiza')),
                ('domicilio_laboral', models.CharField(blank=True, max_length=50, null=True, verbose_name='Domicilio Laboral')),
                ('ayduda_centroa_cual', models.CharField(blank=True, max_length=50, null=True, verbose_name='Especificar Cual')),
                ('jfinterviniente', models.CharField(blank=True, max_length=50, null=True, verbose_name='Juzgado/Fiscalía Interviniente')),
                ('obasistencia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Obligatoriedad de Asistencia')),
                ('detenido', models.CharField(blank=True, max_length=50, null=True, verbose_name='Detenido')),
                ('prohibicion_quien', models.CharField(blank=True, max_length=50, null=True, verbose_name='Hacia quien/es')),
                ('arma_tipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Arma')),
                ('antecedentes_vg', models.CharField(blank=True, max_length=200, null=True, verbose_name='Por VG')),
                ('antecedentes_otros', models.CharField(blank=True, max_length=200, null=True, verbose_name='Otros')),
                ('pddnombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre Completo')),
                ('pddtelefono', models.PositiveIntegerField(blank=True, null=True, verbose_name='Telefono')),
                ('pdddomicilio_conocido', models.CharField(blank=True, max_length=200, null=True, verbose_name='Domicilo Conocido')),
                ('dpanombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre Completo')),
                ('dpatelefono', models.PositiveIntegerField(blank=True, null=True, verbose_name='Telefono')),
                ('dpadomicilio_conocido', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre Completo')),
                ('apanteriodes', models.CharField(blank=True, max_length=50, null=True, verbose_name='Anteriores')),
                ('apvigentes', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vigentes')),
                ('aptratamiento_cual', models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Cual?')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='OBSERVACIONES')),
                ('equipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Equipo')),
                ('fechacreacion', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Fecha')),
                ('baja', models.BooleanField(default=True)),
                ('acceso_arma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acceso_arma', to='encuesta.opcion', verbose_name='¿Tiene Acceso a armas de fuego o similar?')),
                ('aptratamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aptratamiento', to='encuesta.opcion', verbose_name='Tratamiento Farmacologico')),
                ('ayuda_centroa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='encuesta.centroabordaje', verbose_name='¿Como Llega al Centro de Abordaje?')),
                ('categoria_inactividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='encuesta.categoriainactividad', verbose_name='Categoria Inactividad')),
                ('categoria_ocupacional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='encuesta.categoriaocupacional', verbose_name='Categoria Ocupacional')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='encuesta.departamento', verbose_name='Departamento')),
                ('distrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='encuesta.distrito', verbose_name='Distrito')),
                ('estado_civil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='encuesta.estadocivil', verbose_name='Estado Civil')),
                ('miembros_intervinientes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='encuesta.miembrosconvivientes', verbose_name='Miembros Convivientes')),
                ('nacionalidad', models.ForeignKey(default=9, null=True, on_delete=django.db.models.deletion.PROTECT, to='encuesta.nacionalidad', verbose_name='Nacionalidad')),
                ('nivel_educacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='encuesta.educacion', verbose_name='Educacion (Maximo Nivel Alcaanzado)')),
                ('ostiene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ostiene', to='encuesta.opcion', verbose_name='Tiene Obra Social')),
                ('prohibicion_acercamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prohibicion_acercamiento', to='encuesta.opcion', verbose_name='Prohibicion de Acercamiento')),
                ('pulsera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pulsera', to='encuesta.opcion', verbose_name='Pulsera Electronica')),
                ('situacion_laboral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='encuesta.situacionlaboral', verbose_name='Situacion Laboral')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_update', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Encuesta',
                'verbose_name_plural': 'Encuestas',
                'db_table': 'encuesta',
                'ordering': ['id'],
            },
        ),
    ]
