# Generated by Django 3.2.4 on 2022-10-28 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='antecedentes_judiciales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='antecedentes_judiciales', to='encuesta.opcion', verbose_name='Antecedentes Judiciales'),
        ),
    ]
