# Generated by Django 3.2.4 on 2022-12-26 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='fechacreacion',
            field=models.DateField(default=datetime.datetime.now, null=True, verbose_name='Fecha Ficha'),
        ),
    ]
