# Generated by Django 3.2.4 on 2022-11-28 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dispositivo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'dispositivo',
                'verbose_name_plural': 'dispositivo',
                'db_table': 'dispositivo',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='distrito',
            options={'ordering': ['id'], 'verbose_name': 'Distrito', 'verbose_name_plural': 'distritos'},
        ),
        migrations.AddField(
            model_name='equipos',
            name='sigla',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sigla'),
        ),
        migrations.AddField(
            model_name='equipos',
            name='dispositivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_equipos', to='encuesta.dispositivos', verbose_name='Dispositivo'),
        ),
    ]
