# Generated by Django 3.2.4 on 2022-10-24 15:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='fechacreacion',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Fecha Ficha'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='nivel_educacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='encuesta.educacion', verbose_name='Educacion (Maximo Nivel Alcanzado)'),
        ),
    ]
