# Generated by Django 3.2.4 on 2022-10-28 16:45

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0002_alter_encuesta_antecedentes_judiciales'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeisMeses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Tiempo Tratamiento',
                'verbose_name_plural': 'Tiempo Tratamiento',
                'db_table': 'tiempo_tratamiento',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='atps_psico_psiqui',
        ),
        migrations.AddField(
            model_name='encuesta',
            name='atps_psicologico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='psicologico', to='encuesta.opcion', verbose_name='Antecedente Psicologico'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='atps_psiquiatrico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='psiquiatrico', to='encuesta.opcion', verbose_name='Antecedente Psiquiatrico'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='agresor',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Condicion Migratoria'), ('2', 'Estres Psicosocial'), ('3', 'Abuso de Sustancias Psicoactivas'), ('4', 'Antecedentes de Violencia en su Biografia'), ('5', 'Tenencia y uso de Armas'), ('6', 'Antecedentes depresivos'), ('7', 'Presencia de miedo o rechazo a los abandonos'), ('8', 'Inestabilidad anímica'), ('9', 'Egocentrismo')], max_length=17),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='antecedentes_otros',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Delito Contra la Persona'), ('2', 'Delito contra la vida'), ('3', 'Intento de femicidio'), ('4', 'Lesiones Leves'), ('5', 'Lesiones Graves'), ('6', 'Lesiones Gravisimas'), ('7', 'Abuso de Armas (con lesiones)'), ('8', 'Abuso de Armas (sin lesiones)'), ('9', 'Abandono de la persona'), ('10', 'Delitos contra la integridad sexual'), ('11', ' Delitos contra la libertad (Amenaza)'), ('12', ' Delitos contra la libertad (Violacion de Domicilio)'), ('13', ' Delitos contra la propiedad (Hurto)'), ('14', ' Delitos contra la propiedad (Robo)'), ('15', ' Violacion de Domicilio (Extorsión)'), ('16', ' Violacion de Domicilio (Usurpación)'), ('17', ' Violacion de Domicilio (Daños)'), ('18', ' Violacion de Domicilio (Desobediencia)')], max_length=44),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='atps_medicacion_nombre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre - Medicación'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='mujer',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Vulnerabilidad Social'), (2, 'Retractarse de separacion o denuncia al agresor'), (3, 'Presencia de hijo no biológico en la convivencia con el agresor')], max_length=5),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='atps_psico_psiqui_6_meses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atps_psico_psiqui_6_meses', to='encuesta.seismeses', verbose_name='Tratamiento 6 meses'),
        ),
    ]
