# Generated by Django 3.2.4 on 2022-12-26 13:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0002_alter_encuesta_fechacreacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parentesco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Parentesco',
                'verbose_name_plural': 'Parentesco',
                'db_table': 'parentesco',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='encuesta',
            name='mc_apellido',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido:'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='mc_fechanacimiento',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de Nacimiento:'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='mc_nombre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre:'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='parentesco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='encuesta.parentesco', verbose_name='Parentesco:'),
        ),
    ]
