# Generated by Django 3.2.4 on 2022-12-02 14:08

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0002_auto_20221128_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriainactividad',
            name='categoria_inactividad',
            field=models.CharField(max_length=50, verbose_name='Categoría de Inactividad'),
        ),
        migrations.AlterField(
            model_name='categoriaocupacional',
            name='categoria_ocupacion',
            field=models.CharField(max_length=50, verbose_name='Categoría Ocupacional'),
        ),
        migrations.AlterField(
            model_name='centroabordaje',
            name='abordaje_como_llega',
            field=models.CharField(max_length=50, verbose_name='¿Como llega al Centro de Abordaje?'),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='nivel',
            field=models.CharField(max_length=50, verbose_name='Nivel Educativo (Máximo Alcanzado)'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='acceso_arma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acceso_arma', to='encuesta.opcion', verbose_name='¿Tiene acceso a armas de fuego o similar?'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='actividad_laboral',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Actividad que realiza'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='agresor',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Condición Migratoria', 'Condición Migratoria'), ('Estrés Psicosocial', 'Estrés Psicosocial'), ('Abuso de Sustancias Psicoactivas', 'Abuso de Sustancias Psicoactivas'), ('Antecedentes de Violencia en su Biografía', 'Antecedentes de Violencia en su Biografía'), ('Tenencia y uso de Armas', 'Tenencia y uso de Armas'), ('Antecedentes depresivos', 'Antecedentes depresivos'), ('Presencia de miedo o rechazo a los abandonos', 'Presencia de miedo o rechazo a los abandonos'), ('Inestabilidad anímica', 'Inestabilidad anímica'), ('Egocentrismo', 'Egocentrismo')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='antecedentes_otros',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Delito Contra la Persona', 'Delito Contra la Persona'), ('Delito contra la vida', 'Delito contra la vida'), ('Intento de femicidio', 'Intento de femicidio'), ('Lesiones Leves', 'Lesiones Leves'), ('Lesiones Graves', 'Lesiones Graves'), ('Lesiones Gravísimas', 'Lesiones Gravísimas'), ('Abuso de Armas (con lesiones)', 'Abuso de Armas (con lesiones)'), ('Abuso de Armas (sin lesiones)', 'Abuso de Armas (sin lesiones)'), ('Abandono de la persona', 'Abandono de la persona'), ('Delitos contra la integridad sexual', 'Delitos contra la integridad sexual'), ('Delitos contra la libertad (Amenaza)', ' Delitos contra la libertad (Amenaza)'), ('Delitos contra la libertad (Violación de Domicilio)', ' Delitos contra la libertad (Violación de Domicilio)'), ('Delitos contra la propiedad (Hurto)', ' Delitos contra la propiedad (Hurto)'), ('Delitos contra la propiedad (Robo)', ' Delitos contra la propiedad (Robo)'), ('Violación de Domicilio (Extorsión)', ' Violación de Domicilio (Extorsión)'), ('Violación de Domicilio (Usurpación)', ' Violación de Domicilio (Usurpación)'), ('Violación de Domicilio (Daños)', ' Violación de Domicilio (Daños)'), ('Violación de Domicilio (Desobediencia)', ' Violación de Domicilio (Desobediencia)')], max_length=538, null=True),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='atps_psicologico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psicologico', to='encuesta.opcion', verbose_name='Antecedente Psicológico'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='atps_psiquiatrico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psiquiatrico', to='encuesta.opcion', verbose_name='Antecedente Psiquíatrico'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='ayduda_centroa_cual',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Especificar Cúal'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='categoria_inactividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='encuesta.categoriainactividad', verbose_name='Categoría Inactividad'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='categoria_ocupacional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='encuesta.categoriaocupacional', verbose_name='Categoría Ocupacional'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='modalidad_personal',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Domestica', 'Domestica'), ('Institucional', 'Institucional'), ('Laboral', 'Laboral'), ('Contra la libertad reproductiva y obstétrica', 'Contra la libertad reproductiva y obstétrica'), ('Mediática', 'Mediática')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='mujer',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Vulnerabilidad Social', 'Vulnerabilidad Social'), ('Retractarse de separación o denuncia al agresor', 'Retractarse de separación o denuncia al agresor'), ('Presencia de hijo no biológico en la convivencia con el agresor', 'Presencia de hijo no biológico en la convivencia con el agresor')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='nivel_educacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='encuesta.educacion', verbose_name='Educación (Máximo Nivel Alcanzado)'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='prohibicion_acercamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prohibición_acercamiento', to='encuesta.opcion', verbose_name='Prohibición de Acercamiento'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='prohibicion_quien',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Hacia quién/es'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='pulsera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pulsera', to='encuesta.opcion', verbose_name='Pulsera Electrónica'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='situacion',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Relación en convivencia o matrimonial', 'Relación en convivencia o matrimonial'), ('Solicitud de separación por parte de la mujer', 'Solicitud de separación por parte de la mujer'), ('Ideación de celos del estilo posesivos', 'Ideación de celos del estilo posesivos'), ('Transitar embarazo', 'Transitar embarazo'), ('Presedente de conductas de acoso', 'Presedente de conductas de acoso'), ('Conductas de amenazas', 'Conductas de amenazas')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='situacion_laboral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='encuesta.situacionlaboral', verbose_name='Situación Laboral'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='telefono',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='telefonoa',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Teléfono Alternativo'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='tv_familiar',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Física', 'Física'), ('Violencia Psicológica', 'Violencia Psicológica'), ('Violencia Sexual', 'Violencia Sexual'), ('Violencia Económica y patrimonial', 'Violencia Económica y patrimonial'), ('Violencia Simbolica', 'Violencia Simbolica'), ('Violencia Ambiental', 'Violencia Ambiental')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='tv_personal',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Fisica', 'Fisica'), ('Violencia Psicológica', 'Violencia Psicológica'), ('Violencia Sexual', 'Violencia Sexual'), ('Violencia Económica y patrimonial', 'Violencia Económica y patrimonial'), ('Violencia Simbólica', 'Violencia Simbólica'), ('Violencia Ambiental', 'Violencia Ambiental')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incumbenciaseguridad',
            name='incumbencia_seguridad',
            field=models.CharField(max_length=50, verbose_name='Ocupación en la fuerza de seguridad, según incumbencia'),
        ),
        migrations.AlterField(
            model_name='situacionlaboral',
            name='situacion_laboral',
            field=models.CharField(max_length=50, verbose_name='Situación Laboral'),
        ),
    ]
