# Generated by Django 3.2.4 on 2022-12-26 13:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0003_auto_20221226_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='mc_apellido1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido:'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='mc_apellido2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido:'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='mc_apellido3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido:'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='mc_fechanacimiento1',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de Nacimiento:'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='mc_fechanacimiento2',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de Nacimiento:'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='mc_fechanacimiento3',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de Nacimiento:'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='mc_nombre1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre:'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='mc_nombre2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre:'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='mc_nombre3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre:'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='parentesco1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentesco1', to='encuesta.parentesco', verbose_name='Parentesco:'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='parentesco2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentesco2', to='encuesta.parentesco', verbose_name='Parentesco:'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='parentesco3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentesco3', to='encuesta.parentesco', verbose_name='Parentesco:'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='parentesco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentesco', to='encuesta.parentesco', verbose_name='Parentesco:'),
        ),
    ]
