# Generated by Django 3.2.4 on 2022-10-31 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0004_auto_20221030_2338'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModalidadFamiliar',
        ),
        migrations.DeleteModel(
            name='ModalidadPersonal',
        ),
        migrations.DeleteModel(
            name='TipoViolenciaFamiliar',
        ),
        migrations.DeleteModel(
            name='TipoViolenciaPersonal',
        ),
    ]
