# Generated by Django 3.2.4 on 2022-10-31 02:10

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0008_alter_nacionalidad_nacionalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='antecedentes_otros',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Delito Contra la Persona'), (2, 'Delito contra la vida'), (3, 'Intento de femicidio'), (4, 'Lesiones Leves'), (5, 'Lesiones Graves'), (6, 'Lesiones Gravisimas'), (7, 'Abuso de Armas (con lesiones)'), (8, 'Abuso de Armas (sin lesiones)'), (9, 'Abandono de la persona'), (10, 'Delitos contra la integridad sexual'), (11, ' Delitos contra la libertad (Amenaza)'), (12, ' Delitos contra la libertad (Violacion de Domicilio)'), (13, ' Delitos contra la propiedad (Hurto)'), (14, ' Delitos contra la propiedad (Robo)'), (15, ' Violacion de Domicilio (Extorsión)'), (16, ' Violacion de Domicilio (Usurpación)'), (17, ' Violacion de Domicilio (Daños)'), (18, ' Violacion de Domicilio (Desobediencia)')], max_length=44, null=True),
        ),
    ]
