# Generated by Django 3.2.4 on 2022-10-31 14:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0010_auto_20221031_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='observaciones',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='OBSERVACIONES'),
        ),
    ]
