# Generated by Django 3.2.4 on 2022-10-31 15:08

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0011_alter_encuesta_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='agresor',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Condicion Migratoria', 'Condicion Migratoria'), ('Estres Psicosocial', 'Estres Psicosocial'), ('Abuso de Sustancias Psicoactivas', 'Abuso de Sustancias Psicoactivas'), ('Antecedentes de Violencia en su Biografia', 'Antecedentes de Violencia en su Biografia'), ('Tenencia y uso de Armas', 'Tenencia y uso de Armas'), ('Antecedentes depresivos', 'Antecedentes depresivos'), ('Presencia de miedo o rechazo a los abandonos', 'Presencia de miedo o rechazo a los abandonos'), ('Inestabilidad anímica', 'Inestabilidad anímica'), ('Egocentrismo', 'Egocentrismo')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='antecedentes_otros',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Delito Contra la Persona', 'Delito Contra la Persona'), ('Delito contra la vida', 'Delito contra la vida'), ('Intento de femicidio', 'Intento de femicidio'), ('Lesiones Leves', 'Lesiones Leves'), ('Lesiones Graves', 'Lesiones Graves'), ('Lesiones Gravisimas', 'Lesiones Gravisimas'), ('Abuso de Armas (con lesiones)', 'Abuso de Armas (con lesiones)'), ('Abuso de Armas (sin lesiones)', 'Abuso de Armas (sin lesiones)'), ('Abandono de la persona', 'Abandono de la persona'), ('Delitos contra la integridad sexual', 'Delitos contra la integridad sexual'), ('Delitos contra la libertad (Amenaza)', ' Delitos contra la libertad (Amenaza)'), ('Delitos contra la libertad (Violacion de Domicilio)', ' Delitos contra la libertad (Violacion de Domicilio)'), ('Delitos contra la propiedad (Hurto)', ' Delitos contra la propiedad (Hurto)'), ('Delitos contra la propiedad (Robo)', ' Delitos contra la propiedad (Robo)'), ('Violacion de Domicilio (Extorsión)', ' Violacion de Domicilio (Extorsión)'), ('Violacion de Domicilio (Usurpación)', ' Violacion de Domicilio (Usurpación)'), ('Violacion de Domicilio (Daños)', ' Violacion de Domicilio (Daños)'), ('Violacion de Domicilio (Desobediencia)', ' Violacion de Domicilio (Desobediencia)')], max_length=538, null=True),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='modalidad_familiar',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Domestica', 'Domestica'), ('Institucional', 'Institucional'), ('Laboral', 'Laboral'), ('Contra la libertad reprodictiva y obstétrica', 'Contra la libertad reprodictiva y obstétrica'), ('Mediatica', 'Mediatica')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='modalidad_personal',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Domestica', 'Domestica'), ('Institucional', 'Institucional'), ('Laboral', 'Laboral'), ('Contra la libertad reprodictiva y obstétrica', 'Contra la libertad reprodictiva y obstétrica'), ('Mediatica', 'Mediatica')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='mujer',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Vulnerabilidad Social', 'Vulnerabilidad Social'), ('Retractarse de separacion o denuncia al agresor', 'Retractarse de separacion o denuncia al agresor'), ('Presencia de hijo no biológico en la convivencia con el agresor', 'Presencia de hijo no biológico en la convivencia con el agresor')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='OBSERVACIONES'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='situacion',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Relacion en convivencia o matrimonial', 'Relacion en convivencia o matrimonial'), ('Solicitud de separacion por parte de la mujer', 'Solicitud de separacion por parte de la mujer'), ('ideación de celos del estilo posesivos', 'ideación de celos del estilo posesivos'), ('Transitar embarazo', 'Transitar embarazo'), ('presedente de conductas de acoso', 'presedente de conductas de acoso'), ('conductas de amenazas', 'conductas de amenazas')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='tv_familiar',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Fisica', 'Fisica'), ('Violencia Psicologica', 'Violencia Psicologica'), ('Violencia Sexual', 'Violencia Sexual'), ('Violencia Economica y patrimonial', 'Violencia Economica y patrimonial'), ('Violencia Simbolica', 'Violencia Simbolica'), ('Violencia Ambiental', 'Violencia Ambiental')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='tv_personal',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Fisica', 'Fisica'), ('Violencia Psicologica', 'Violencia Psicologica'), ('Violencia Sexual', 'Violencia Sexual'), ('Violencia Economica y patrimonial', 'Violencia Economica y patrimonial'), ('Violencia Simbolica', 'Violencia Simbolica'), ('Violencia Ambiental', 'Violencia Ambiental')], max_length=200, null=True),
        ),
    ]
