# Generated by Django 3.2.4 on 2022-11-04 12:50

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0013_auto_20221101_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='agresor',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Condicion Migratoria', 'Condicion Migratoria'), ('Estres Psicosocial', 'Estres Psicosocial'), ('Abuso de Sustancias Psicoactivas', 'Abuso de Sustancias Psicoactivas'), ('Antecedentes de Violencia en su Biografia', 'Antecedentes de Violencia en su Biografia'), ('Tenencia y uso de Armas', 'Tenencia y uso de Armas'), ('Antecedentes depresivos', 'Antecedentes depresivos'), ('Presencia de miedo o rechazo a los abandonos', 'Presencia de miedo o rechazo a los abandonos'), ('Inestabilidad anímica', 'Inestabilidad anímica'), ('Egocentrismo', 'Egocentrismo')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='modalidad_familiar',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Domestica', 'Domestica'), ('Institucional', 'Institucional'), ('Laboral', 'Laboral'), ('Contra la libertad reprodictiva y obstétrica', 'Contra la libertad reprodictiva y obstétrica'), ('Mediatica', 'Mediatica')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='modalidad_personal',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Domestica', 'Domestica'), ('Institucional', 'Institucional'), ('Laboral', 'Laboral'), ('Contra la libertad reprodictiva y obstétrica', 'Contra la libertad reprodictiva y obstétrica'), ('Mediatica', 'Mediatica')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='mujer',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Vulnerabilidad Social', 'Vulnerabilidad Social'), ('Retractarse de separacion o denuncia al agresor', 'Retractarse de separacion o denuncia al agresor'), ('Presencia de hijo no biológico en la convivencia con el agresor', 'Presencia de hijo no biológico en la convivencia con el agresor')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='situacion',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Relacion en convivencia o matrimonial', 'Relacion en convivencia o matrimonial'), ('Solicitud de separacion por parte de la mujer', 'Solicitud de separacion por parte de la mujer'), ('ideación de celos del estilo posesivos', 'ideación de celos del estilo posesivos'), ('Transitar embarazo', 'Transitar embarazo'), ('presedente de conductas de acoso', 'presedente de conductas de acoso'), ('conductas de amenazas', 'conductas de amenazas')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='tv_familiar',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Fisica', 'Fisica'), ('Violencia Psicologica', 'Violencia Psicologica'), ('Violencia Sexual', 'Violencia Sexual'), ('Violencia Economica y patrimonial', 'Violencia Economica y patrimonial'), ('Violencia Simbolica', 'Violencia Simbolica'), ('Violencia Ambiental', 'Violencia Ambiental')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='tv_personal',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Fisica', 'Fisica'), ('Violencia Psicologica', 'Violencia Psicologica'), ('Violencia Sexual', 'Violencia Sexual'), ('Violencia Economica y patrimonial', 'Violencia Economica y patrimonial'), ('Violencia Simbolica', 'Violencia Simbolica'), ('Violencia Ambiental', 'Violencia Ambiental')], max_length=200, null=True),
        ),
    ]
